import PDFDocument from 'pdfkit';
import { Readable } from 'stream';

export type ExportFormat = 'pdf' | 'html' | 'docx';

interface ExportData {
  projectName: string;
  businessName?: string;
  outputs: Array<{
    title: string;
    content: string;
    type: string;
  }>;
  generatedAt: Date;
}

export function exportToPDF(data: ExportData): Buffer {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: 'A4',
        margin: 50,
      });

      const chunks: Buffer[] = [];

      doc.on('data', (chunk: Buffer) => {
        chunks.push(chunk);
      });

      doc.on('end', () => {
        resolve(Buffer.concat(chunks));
      });

      doc.on('error', reject);

      // Title page
      doc.fontSize(32).font('Helvetica-Bold').text('ZODIAC 13', { align: 'center' });
      doc.fontSize(18).font('Helvetica').text('AI Content Generation Report', { align: 'center' });
      doc.moveDown();

      doc.fontSize(12).text(`Project: ${data.projectName}`);
      doc.text(`Business: ${data.businessName || 'N/A'}`);
      doc.text(`Generated: ${data.generatedAt.toLocaleDateString()}`);
      doc.addPage();

      // Table of contents
      doc.fontSize(16).font('Helvetica-Bold').text('Table of Contents');
      doc.moveDown(0.5);

      let pageNum = 3;
      data.outputs.forEach((output) => {
        doc.fontSize(11).text(`${output.title.replace(/_/g, ' ')} ........... page ${pageNum}`);
        pageNum++;
      });

      doc.addPage();

      // Content
      data.outputs.forEach((output) => {
        doc.fontSize(14).font('Helvetica-Bold').text(output.title.replace(/_/g, ' '));
        doc.moveDown(0.3);
        doc.fontSize(10).font('Helvetica').text(output.content, {
          align: 'left',
          width: 500,
        });
        doc.addPage();
      });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}

export function exportToHTML(data: ExportData): string {
  const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${data.projectName} - ZODIAC 13 Report</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      line-height: 1.6;
      color: #333;
      background: #f5f5f5;
    }
    .container {
      max-width: 900px;
      margin: 0 auto;
      background: white;
      padding: 40px;
    }
    h1 {
      font-size: 2.5em;
      margin-bottom: 10px;
      color: #2575fc;
    }
    h2 {
      font-size: 1.8em;
      margin: 30px 0 20px 0;
      color: #6a11cb;
      border-bottom: 2px solid #2575fc;
      padding-bottom: 10px;
    }
    .metadata {
      background: #f9f9f9;
      padding: 15px;
      border-radius: 5px;
      margin-bottom: 30px;
      border-left: 4px solid #2575fc;
    }
    .metadata p {
      margin: 5px 0;
    }
    .content {
      white-space: pre-wrap;
      background: #fafafa;
      padding: 20px;
      border-radius: 5px;
      margin-bottom: 30px;
      border: 1px solid #eee;
    }
    .page-break {
      page-break-after: always;
      margin-bottom: 50px;
    }
    footer {
      text-align: center;
      margin-top: 50px;
      padding-top: 20px;
      border-top: 1px solid #ddd;
      color: #666;
      font-size: 0.9em;
    }
    @media print {
      body {
        background: white;
      }
      .container {
        padding: 20px;
      }
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>🚀 ZODIAC 13</h1>
    <h2>AI Content Generation Report</h2>

    <div class="metadata">
      <p><strong>Project:</strong> ${data.projectName}</p>
      <p><strong>Business:</strong> ${data.businessName || 'N/A'}</p>
      <p><strong>Generated:</strong> ${data.generatedAt.toLocaleString()}</p>
    </div>

    ${data.outputs
      .map(
        (output) => `
    <div class="page-break">
      <h2>${output.title.replace(/_/g, ' ')}</h2>
      <div class="content">${output.content}</div>
    </div>
    `
      )
      .join('')}

    <footer>
      <p>Generated by ZODIAC 13 - AI Content Generation Platform</p>
      <p>© 2024 All rights reserved</p>
    </footer>
  </div>
</body>
</html>
  `;

  return htmlContent;
}

export function exportToDOCX(data: ExportData): Buffer {
  // Simplified DOCX export (returns HTML as fallback)
  // For full DOCX support, integrate with 'docx' npm package
  const docxContent = `
Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document

Project: ${data.projectName}
Business: ${data.businessName}
Generated: ${data.generatedAt.toLocaleString()}

${data.outputs.map((output) => `\n${output.title}\n${output.content}\n`).join('\n---\n')}
  `.trim();

  return Buffer.from(docxContent, 'utf-8');
}

export async function exportOutputs(
  data: ExportData,
  format: ExportFormat
): Promise<Buffer> {
  switch (format) {
    case 'pdf':
      return exportToPDF(data);
    case 'html':
      return Buffer.from(exportToHTML(data), 'utf-8');
    case 'docx':
      return exportToDOCX(data);
    default:
      throw new Error(`Unsupported format: ${format}`);
  }
}
