name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ '8.1', '8.2' ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer
        coverage: none

    - name: Get composer cache dir
      id: composer-cache-dir
      run: echo "COMPOSER_CACHE_DIR=$(composer config cache-files-dir --global)" >> $GITHUB_ENV

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer dependencies and cache
      uses: actions/cache@v3
      with:
        path: |
          vendor
          ${{ env.COMPOSER_CACHE_DIR }}
        key: ${{ runner.os }}-php-${{ matrix.php }}-${{ hashFiles('**/composer.lock', '**/composer.json') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.php }}-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-interaction

    # Uncomment and update if you have tests:
    # - name: Run test suite
    #   run: composer run-script test
